#!/bin/bash

PROJECT_PATH=$(cd "$(dirname $0)/../"; pwd)

docker stop nginx || true
docker rm nginx || true
docker run -d \
    -v $PROJECT_PATH/.devcontainer:/devcontainer \
    -v $PROJECT_PATH/.devcontainer/nginx.conf:/etc/nginx/nginx.conf \
    --network host \
    --name nginx \
    nginx
