#!/bin/bash

PROJECT_PATH=$(cd "$(dirname $0)"; pwd)

cd $PROJECT_PATH

# make tempdir
TEMPDIR=$(mktemp -d)
git clone https://github.com/DrCloy/reacton-v2.git $TEMPDIR
rsync -av --exclude='.git' --exclude-from="$PROJECT_PATH/.gitignore" "$PROJECT_PATH"/ "$TEMPDIR"/

cd $TEMPDIR
git add .
git commit -m "publish $(date +'%Y-%m-%dT%H:%M:%S')"
git push origin main
rm -rf $TEMPDIR